### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [kwanko/gtm-conversion-tag#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) injectScript should have the callback functions onSuccess and onFailure which are not present. Please update accordingly. Please refer to [https://developers.google.com/tag-manager/templates/api](https://developers.google.com/tag-manager/templates/api) for more information.

2) User instructions to install the template should direct users to install the gallery version of the template by clicking on the "Search Gallery" button in the template tab to add the gallery template.

**Comment by skodev** [comment]
Hi @praveena-pappu, thanks for your reply.
I've just pushed some modifications taking in consideration your feedback (cf [a0b75cd](https://github.com/kwanko/gtm-conversion-tag/commit/a0b75cd2faa6b27316a021ff98840df84bd55a03)
Please let me know if further modifications are required for validation.
Thank you.

**Comment by skodev** [comment]
Template is online, so I close this issue.
